Repository SF-ALGO-08/algorithm, pull requests merged in 2021-03, with the labels that each got.

#54 양동혁: BOJ 1300 K번째 수
  SmiteFLame/BOJ_1300/BOJ_1300.java
  SmiteFLame/BOJ_1300/README.md
Labels: 이분 탐색

#53 진미령 : BOJ1300 K번째 수
  miir-jj/BOJ1300/BOJ1300.java
  miir-jj/BOJ1300/BOJ1300_1.java
Labels: 이분 탐색

#52 진미령 : BOJ2075 N번째 큰 수
  miir-jj/BOJ2075/BOJ2075.java
  miir-jj/BOJ2075/README.md
Labels: 우선순위 큐

#51 진미령 : BOJ2003 수들의 합2
  miir-jj/BOJ2003/BOJ2003.java
  miir-jj/BOJ2003/README.md
Labels: 투 포인터

#50 남준영: BOJ 1300 K번째 수
  jun7867/BOJ1300/BOJ_G3_1300_K번째수.java
  jun7867/BOJ1300/README.md
  jun7867/BOJ2370/BOJ_G3_2370_시장선거포스터.java
  jun7867/BOJ2370/README.md
Labels: Parametric Search, 이분 탐색

#49 김민지: BOJ 13030 K번째 수
  mjkim103301/BOJ1300/BOJ1300.java
  mjkim103301/BOJ1300/BOJ1300_2.java
  mjkim103301/BOJ1300/README.md
Labels: 이분 탐색

#47 양동혁: BOJ 2075 N번째 큰수
  SmiteFLame/BOJ_2075/BOJ_2075.java
  SmiteFLame/BOJ_2075/README.md
Labels: 우선순위 큐

#46 양동혁: BOJ 2003 수들의 합 2
  SmiteFLame/BOJ_2003/BOJ_2003.java
  SmiteFLame/BOJ_2003/README.md
Labels: 투 포인터

#41 김민지: BOJ 2075 N번째 큰 수
  mjkim103301/BOJ2075/BOJ2075.java
  mjkim103301/BOJ2075/README.md
Labels: 우선순위 큐

#40 김민지: BOJ 2003 수들의 합2
  mjkim103301/BOJ2003/BOJ2003.java
  mjkim103301/BOJ2003/BOJ2003_2.java
  mjkim103301/BOJ2003/README.md
Labels: 투 포인터

#71 진미령 : BOJ1793 타일링
  miir-jj/BOJ1793/BOJ1793.java
  miir-jj/BOJ1793/README.md
Labels: DP

#70 진미령 : BOJ1563 개근상
  miir-jj/BOJ1563/BOJ1563.java
  miir-jj/BOJ1563/README.md
Labels: DP

#69 진미령 : BOJ17144 미세먼지 안녕!
  miir-jj/BOJ17144/BOJ17144.java
  miir-jj/BOJ17144/README.md
Labels: 시뮬레이션

#68 김민지: BOJ 1563, 1793, 17144
  mjkim103301/BOJ1563/BOJ1563_개근상.java
  mjkim103301/BOJ1563/README.md
  mjkim103301/BOJ17144/BOJ17144_미세먼지안녕.java
  mjkim103301/BOJ17144/README.md
  mjkim103301/BOJ1793/BOJ1793_타일링.java
  mjkim103301/BOJ1793/README.md
Labels: 다이나믹 프로그래밍, 시뮬레이션

#67 이서영: BOJ1563 개근상
  Seoyoung2/BOJ1563/Main_1563.java
  Seoyoung2/BOJ1563/README.md
Labels: DP

#66 남준영: BOJ 1563 개근상
  jun7867/BOJ1563/BOJ_G4_1563_개근상.java
  jun7867/BOJ1563/README.md
Labels: 다이나믹 프로그래밍

#64 양동혁:BOJ 1563 개근상
  SmiteFLame/BOJ_1563/BOJ_1563.java
  SmiteFLame/BOJ_1563/README.md
Labels: 다이나믹 프로그래밍

#63 박현우 : BOJ 1793 타일링
  Hyeonwoo-Park/BOJ1793/README.md
  Hyeonwoo-Park/BOJ1793/Tiling.java
Labels: DP

#61 남준영 : BOJ 17144 미세먼지 안녕!
  jun7867/BOJ17144/BOJ_G5_17144_미세먼지안녕.java
  jun7867/BOJ17144/README.md
Labels: 시뮬레이션

#60 양동혁: BOJ 1793 타일링
  SmiteFLame/BOJ_1793/BOJ_1793.java
  SmiteFLame/BOJ_1793/README.md
Labels: 다이나믹 프로그래밍

#59 양동혁: BOJ 17144 미세먼지 안녕!
  SmiteFLame/BOJ_17144/BOJ_17144.java
  SmiteFLame/BOJ_17144/README.md
Labels: 시뮬레이션

#58 박현우 : BOJ 1563 개근상
  Hyeonwoo-Park/BOJ1563/AttendanceAward.java
  Hyeonwoo-Park/BOJ1563/README.md
Labels: DP

#57 남준영: BOJ 1793 타일링
  jun7867/BOJ1793/BOJ_S1_1793_타일링.java
  jun7867/BOJ1793/README.md
Labels: 다이나믹 프로그래밍

#56 박현우 : BOJ 17144 미세먼지 안녕!
  Hyeonwoo-Park/BOJ17144/Dust.java
  Hyeonwoo-Park/BOJ17144/README.md
Labels: 시뮬레이션

#85 진미령 : BOJ17136 색종이 붙이기
  miir-jj/BOJ17136/BOJ17136.java
  miir-jj/BOJ17136/README.md
Labels: DFS/BFS, 재귀/백트래킹

#84 진미령 : BOJ2629 양팔저울
  miir-jj/BOJ2629/BOJ2629.java
  miir-jj/BOJ2629/README.md
Labels: DP

#83 진미령 : BOJ2631 줄세우기
  miir-jj/BOJ2631/BOJ2631.java
  miir-jj/BOJ2631/BOJ2631_1.java
  miir-jj/BOJ2631/README.md
Labels: DP, LIS

#81 김민지: BOJ 2629 양팔저울, 2631 줄세우기, 17136 색종이 붙이기
  mjkim103301/BOJ17136_색종이붙이기/BOJ17136.java
  mjkim103301/BOJ17136_색종이붙이기/README.md
  mjkim103301/BOJ2629_양팔저울/BOJ2629.java
  mjkim103301/BOJ2629_양팔저울/README.md
  mjkim103301/BOJ2631_줄세우기/BOJ2631.java
  mjkim103301/BOJ2631_줄세우기/README.md
Labels: DP, LIS, 완전탐색, 재귀/백트래킹

#77 박현우 : BOJ 2631 줄세우기
  Hyeonwoo-Park/BOJ2631/LineUp.java
  Hyeonwoo-Park/BOJ2631/README.md
Labels: LIS

#76 양동혁: BOJ 2631 줄세우기
  SmiteFLame/BOJ_2631/BOJ_2631.java
  SmiteFLame/BOJ_2631/README.md
Labels: LIS, 다이나믹 프로그래밍

#75 남준영: BOJ2629 양팔저울
  jun7867/BOJ2629/BOJ_G2_2629_양팔저울.java
  jun7867/BOJ2629/README.md
Labels: DP

#74 양동혁: BOJ_17136 색종이붙이기
  SmiteFLame/BOJ_17136/BOJ_17136.java
  SmiteFLame/BOJ_17136/README.md
Labels: 재귀/백트래킹

#72 남준영: BOJ2631 줄세우기
  jun7867/BOJ2631/BOJ_G5_2631_줄세우기.java
  jun7867/BOJ2631/README.md
Labels: LIS, 다이나믹 프로그래밍
