Repository SF-ALGO-08/algorithm, pull requests merged in 2021-05, with the labels that each got.

#157 진미령 : BOJ2251 물통
  miir-jj/BOJ2251/BOJ2251.java
Labels: BFS

#155 진미령 : BOJ12100 2048(Easy)
  miir-jj/BOJ12100/BOJ12100.java
  miir-jj/BOJ12100/README.md
Labels: 구현

#154 양동혁: BOJ 12100 2048(Easy)
  SmiteFLame/BOJ_12100/BOJ_12100.java
  SmiteFLame/BOJ_12100/README.md
Labels: DFS, 시뮬레이션

#149 양동혁: BOJ 2251 물통
  SmiteFLame/BOJ_2251/BOJ_2075.java
  SmiteFLame/BOJ_2251/README.md
Labels: BFS

#143 김민지: BOJ 18222 투에-모스 문자열
  mjkim103301/BOJ18222/BOJ18222_투에모스문자열.java
  mjkim103301/BOJ18222/README.md
Labels: 재귀/백트래킹

#165 남준영 : BOJ 15486 퇴사2
  jun7867/BOJ15486/BOJ_S1_15486_퇴사2.java
  jun7867/BOJ15486/README.md
Labels: DP

#164 남준영 :BOJ20291 파일 정리
  jun7867/BOJ20291/BOJ_S4_20291_파일정리.java
  jun7867/BOJ20291/README.md
Labels: Map, 정렬

#163 양동혁: BOJ 15486 퇴사2
  SmiteFLame/BOJ_15486/BOJ_15486.java
  SmiteFLame/BOJ_15486/README.md
Labels: DP

#162 양동혁: BOJ 20165 인내의 도미노 장인 호석
  SmiteFLame/BOJ_20165/BOJ_20165.java
  SmiteFLame/BOJ_20165/README.md
Labels: 시뮬레이션

#170 양동혁: BOJ_15666 N과 M(12)
  SmiteFLame/BOJ_15666/BOJ_15666.java
  SmiteFLame/BOJ_15666/README.md
Labels: 부분집합

#174 양동혁: BOJ 14002 가장 긴 증가하는 부분 수열 4
  SmiteFLame/BOJ_14002/BOJ_14002.java
  SmiteFLame/BOJ_14002/README.md
Labels: DP

#175 김민지: BOJ 13549, 14002, 15666
  mjkim103301/BOJ13549/BOJ13549_숨바꼭질3.java
  mjkim103301/BOJ13549/README.md
  mjkim103301/BOJ14002/BOJ14002_가장 긴 증가하는 부분수열4.java
  mjkim103301/BOJ14002/README.md
  mjkim103301/BOJ15666/BOJ15666_N과M12.java
  mjkim103301/BOJ15666/README.md
Labels: BFS, DP, LIS
