Repository SF-ALGO-08/algorithm, pull requests merged in 2021-04, with the labels that each got.

#99 진미령 : BOJ1922 네트워크 연결
  miir-jj/BOJ1922/BOJ1922_Kruskal.java
  miir-jj/BOJ1922/README.md
Labels: 최소 신장 트리(MST)

#98 진미령 : BOJ16918 봄버맨
  miir-jj/BOJ16918/BOJ16918.java
  miir-jj/BOJ16918/README.md
Labels: DFS/BFS, 시뮬레이션

#97 진미령 : BOJ17609 회문
  miir-jj/BOJ17609/BOJ17609.java
  miir-jj/BOJ17609/README.md
Labels: 투 포인터

#96 박현우 : BOJ 1922 네트워크 연결
  Hyeonwoo-Park/BOJ1922/Network.java
  Hyeonwoo-Park/BOJ1922/README.md
Labels: 최소 신장 트리(MST)

#95 남준영: BOJ1922 네트워크 연결
  jun7867/BOJ1922/BOJ_G4_1922_네트워크연결.java
  jun7867/BOJ1922/README.md
Labels: 최소 신장 트리(MST)

#92 양동혁: BOJ 16918 붐버맨
  SmiteFLame/BOJ_16918/BOJ_16918.java
  SmiteFLame/BOJ_16918/README.md
Labels: 시뮬레이션

#91 김민지: BOJ 16918, 17609, 1922
  mjkim103301/BOJ16918/BOJ16918_봄버맨.java
  mjkim103301/BOJ16918/README.md
  mjkim103301/BOJ17609/BOJ17609_회문.java
  mjkim103301/BOJ17609/README.md
  mjkim103301/BOJ1922/BOJ1922_네트워크연결.java
  mjkim103301/BOJ1922/README.md
Labels: 시뮬레이션, 최소 신장 트리(MST), 투 포인터

#89 양동혁: BOJ 1922 네트워크 연결
  SmiteFLame/BOJ_1922/BOJ_1922.java
  SmiteFLame/BOJ_1922/README.md
Labels: 최소 신장 트리(MST)

#88 양동혁: BOJ 17609 회문
  SmiteFLame/BOJ_17609/BOJ_17609.java
  SmiteFLame/BOJ_17609/README.md
Labels: 투 포인터

#87 남준영: BOJ16918 붐버맨
  jun7867/BOJ16918/BOJ_S1_16918_붐버맨.java
  jun7867/BOJ16918/README.md
Labels: 시뮬레이션

#86 남준영: BOJ17609 회문
  jun7867/BOJ17609/BOJ_S1_17609_회문.java
  jun7867/BOJ17609/README.md
Labels: 투 포인터

#116 양동혁: BOJ 17281 ⚾
  SmiteFLame/BOJ_17281/BOJ_17281.java
  SmiteFLame/BOJ_17281/README.md
Labels: 시뮬레이션

#115 진미령 : BOJ5567 결혼식
  miir-jj/BOJ5567/BOJ5567.java
  miir-jj/BOJ5567/README.md
Labels: DFS/BFS

#114 진미령 : BOJ2302 극장좌석
  miir-jj/BOJ2302/BOJ2302.java
  miir-jj/BOJ2302/README.md
Labels: DP

#113 진미령 : BOJ17281 ⚾
  miir-jj/BOJ17281/BOJ17281.java
  miir-jj/BOJ17281/README.md
Labels: 구현

#110 김민지: BOJ2302 극장 좌석
  mjkim103301/BOJ2302/BOJ2302_극장좌석.java
  mjkim103301/BOJ2302/README.md
Labels: DP

#109 김민지: BOJ17281 ⚾
  mjkim103301/BOJ17281/BOJ17281_⚾.java
  mjkim103301/BOJ17281/BOJ17281_야구_nextPermutation.java
  mjkim103301/BOJ17281/BOJ17281_야구_switch.java
  mjkim103301/BOJ17281/README.md
Labels: 구현, 순열/조합, 완전탐색

#107 남준영: BOJ 17281 ⚾
  jun7867/BOJ17281/BOJ_G4_17281_baseball.java
  jun7867/BOJ17281/README.md
Labels: 순열/조합, 시뮬레이션

#105 남준영: BOJ2302 극장 좌석
  jun7867/BOJ2302/BOJ_S1_2302_극장좌석.java
  jun7867/BOJ2302/README.md
Labels: DP

#103 양동혁: BOJ 5567 결혼식
  SmiteFLame/BOJ_5567/BOJ_5567.java
  SmiteFLame/BOJ_5567/README.md
Labels: 구현

#128 남준영 :BOJ1034 램프
  jun7867/BOJ1034/BOJ_G4_1034_램프.java
  jun7867/BOJ1034/README.md
Labels: 완전탐색

#134 진미령 : BOJ12847 꿀 아르바이트
  miir-jj/BOJ12847/BOJ12847.java
  miir-jj/BOJ12847/README.md
Labels: 누적합

#133 진미령 : BOJ7507 올림픽게임
  miir-jj/BOJ7507/BOJ7507.java
  miir-jj/BOJ7507/README.md
Labels: 그리디

#126 양동혁: BOJ 7505 올림픽 게임
  SmiteFLame/BOJ_7507/BOJ_7507.java
  SmiteFLame/BOJ_7507/README.md
Labels: 그리디

#125 양동혁: BOJ 12847 꿀 아르바이트
  SmiteFLame/BOJ_12847/BOJ_12847.java
  SmiteFLame/BOJ_12847/README.md
Labels: 누적합

#123 남준영: BOJ7507 올림픽게임
  jun7867/BOJ7507/BOJ_S1_7507_올림픽게임.java
  jun7867/BOJ7507/README.md
Labels: 활동 선택

#121 김민지: BOJ7507 올림픽 게임
  mjkim103301/BOJ7507/BOJ7507_올림픽게임.java
  mjkim103301/BOJ7507/README.md
Labels: 그리디

#120 김민지: BOJ12847 꿀 아르바이트
  mjkim103301/BOJ12847/BOJ12847_꿀아르바이트.java
  mjkim103301/BOJ12847/README.md
Labels: 누적합

#119 박현우 : BOJ7507 올림픽 게임
  Hyeonwoo-Park/BOJ7507/Olympic.java
  Hyeonwoo-Park/BOJ7507/README.md
Labels: 그리디

#118 박현우 : BOJ1034 램프
  Hyeonwoo-Park/BOJ1034/Lamp.java
  Hyeonwoo-Park/BOJ1034/README.md
Labels: 완전탐색

#148 진미령 : BOJ16973 직사각형 탈출
  miir-jj/BOJ16973/BOJ16973.java
  miir-jj/BOJ16973/BOJ16973.md
Labels: DFS/BFS

#147 진미령 : BOJ1327 소트게임
  miir-jj/BOJ1327/BOJ1327.java
  miir-jj/BOJ1327/BOJ1327.md
Labels: DFS/BFS

#144 김민지: BOJ 16973 직사각형 탈출
  mjkim103301/BOJ16973/BOJ16973_직사각형탈출.java
  mjkim103301/BOJ16973/README.md
Labels: DFS/BFS

#142 김민지: BOJ 1327 소트 게임
  mjkim103301/BOJ1327/BOJ1327_소트게임.java
  mjkim103301/BOJ1327/README.md
Labels: DFS/BFS, 문자열

#138 양동혁: BOJ 16973 직사각형 탈출
  SmiteFLame/BOJ_16973/BOJ_16973.java
  SmiteFLame/BOJ_16973/README.md
Labels: DFS/BFS

#136 양동혁: BOJ 1327 소트 게임
  SmiteFLame/BOJ_1327/BOJ_1327.java
  SmiteFLame/BOJ_1327/README.md
Labels: DFS/BFS
