Repository SF-ALGO-08/algorithm, pull requests merged in 2021-02, with the labels that each got.

#9 김민지_1주차_BOJ_1182 부분수열의 합 / 2504 괄호의 값 / 17135 캐슬 디펜스
  mjkim103301/BOJ/BOJ.java
  mjkim103301/BOJ/README.md
  mjkim103301/BOJ1182/BOJ1182.java
  mjkim103301/BOJ1182/README.md
  mjkim103301/BOJ1234/abce.java
  mjkim103301/BOJ17135/BOJ17135.java
  mjkim103301/BOJ17135/README.md
  mjkim103301/BOJ2504/BOJ2504.java
  mjkim103301/BOJ2504/README.md
Labels: DFS/BFS, 구현, 그래프, 스택/큐, 시뮬레이션, 완전탐색, 재귀/백트래킹

#7 남준영: 1주차 (2504 괄호의 값 , 17135 캐슬 디펜스, 1182 부분 수열의 합)
  jun7867/BOJ1182/Main_1182.java
  jun7867/BOJ1182/README.md
  jun7867/BOJ17135/17135.java
  jun7867/BOJ17135/README.md
  jun7867/BOJ2504/Main_2504.java
  jun7867/BOJ2504/README.md
Labels: DFS/BFS, 스택/큐

#4 양동혁: BOJ1182 부분 수열의 합
  SmiteFLame/BOJ_1182/BOJ_1182.java
  SmiteFLame/BOJ_1182/README.md
Labels: 순열/조합

#3 양동혁: BOJ2504 괄호의 값
  SmiteFLame/BOJ_2504/BOJ_2504.java
  SmiteFLame/BOJ_2504/README.md
Labels: 스택/큐

#6 양동혁: BOJ 17135 캐슬 디펜스
  SmiteFLame/BOJ_17135/BOJ_17135.java
  SmiteFLame/BOJ_17135/README.md
Labels: 순열/조합, 시뮬레이션

#10 김민지: BOJ 1303 전쟁-전투
  mjkim103301/BOJ1182/BOJ1182.java
  mjkim103301/BOJ1182/README.md
  mjkim103301/BOJ1303/BOJ1303.java
  mjkim103301/BOJ1303/README.md
  mjkim103301/BOJ17135/BOJ17135.java
  mjkim103301/BOJ17135/README.md
  mjkim103301/BOJ2504/BOJ2504.java
  mjkim103301/BOJ2504/README.md
  mjkim103301/README.md
Labels: DFS/BFS, 그래프

#11 김민지: BOJ 14719 빗물
  mjkim103301/1week/BOJ1182/BOJ1182.java
  mjkim103301/1week/BOJ1182/README.md
  mjkim103301/1week/BOJ17135/BOJ17135.java
  mjkim103301/1week/BOJ17135/README.md
  mjkim103301/1week/BOJ2504/BOJ2504.java
  mjkim103301/1week/BOJ2504/README.md
  mjkim103301/BOJ14719/BOJ14719.java
  mjkim103301/BOJ14719/README.md
Labels: 구현, 시뮬레이션

#12 남준영: BOJ 14719 빗물
  jun7867/BOJ14719/BOJ_G5_14719.java
  jun7867/BOJ14719/README.md
Labels: 구현

#16 양동혁: BOJ 1303 전쟁-전투
  SmiteFLame/BOJ_1303/BOJ_1303.java
  SmiteFLame/BOJ_1303/README.md
Labels: DFS/BFS

#17 양동혁: BOJ 14719 빗물
  SmiteFLame/BOJ_14719/BOJ_14719.java
  SmiteFLame/BOJ_14719/README.md
Labels: 구현

#18 박현우: BOJ 14719 빗물
  Hyeonwoo-Park/BOJ14719/Rainwater.java
  Hyeonwoo-Park/BOJ14719/readme.md
Labels: 구현

#19 박현우: BOJ 1303 전쟁 - 전투
  Hyeonwoo-Park/BOJ1303/War.java
  Hyeonwoo-Park/BOJ1303/readme.md
Labels: DFS/BFS

#20 양동혁: BOJ 16637 괄호 추가하기
  SmiteFLame/BOJ_16637/BOJ_16637.java
  SmiteFLame/BOJ_16637/README.md
Labels: 순열/조합

#25 진미령 : BOJ 14719 빗물
  miir-jj/BOJ14719/BOJ14719.java
  miir-jj/BOJ14719/README.md
Labels: 구현

#26 진미령 : BOJ 1303 전쟁 - 전투
  miir-jj/BOJ1303/BOJ1303.java
  miir-jj/BOJ1303/README.md
Labels: DFS/BFS

#27 박현우: BOJ 16637 괄호 추가하기
  Hyeonwoo-Park/BOJ16637/BraketAppend.java
  Hyeonwoo-Park/BOJ16637/README.md
Labels: 완전탐색

#37 남준영: BOJ 1325 효율적인 해킹
  jun7867/BOJ1325/BOJ_S2_1325_효율적인해킹.java
  jun7867/BOJ1325/README.md
Labels: DFS/BFS

#31 양동혁: BOJ 1325 효율적인 해킹
  SmiteFLame/BOJ_1325/BOJ_1325.java
  SmiteFLame/BOJ_1325/README.md
Labels: DFS/BFS

#30 양동혁: BOJ 2370 시장 선거 포스터
  SmiteFLame/BOJ_2370/BOJ_2370.java
  SmiteFLame/BOJ_2370/README.md
Labels: 구현

#29 양동혁: BOJ 2615 오목
  SmiteFLame/BOJ_2615/BOJ_2615.java
  SmiteFLame/BOJ_2615/README.md
Labels: 시뮬레이션

#28 남준영: BOJ 2615 오목
  jun7867/BOJ2615/BOJ_S3_2615_오목.java
  jun7867/BOJ2615/README.md
Labels: DFS/BFS
